/* CSS - Cascading Style Sheet */
/* Palette color codes */
/* Palette URL: http://paletton.com/#uid=12i0u0kllll24uRbHq6uZg-UObP */

/* Feel free to copy&paste color codes to your application */


/* As hex codes */

.color-primary-0 { color: #81A035 }	/* Main Primary color */
.color-primary-1 { color: #E3E8D9 }
.color-primary-2 { color: #AFC47C }
.color-primary-3 { color: #5A7C04 }
.color-primary-4 { color: #3F5900 }



/* As RGBa codes */

.rgba-primary-0 { color: rgba(129,160, 53,1) }	/* Main Primary color */
.rgba-primary-1 { color: rgba(227,232,217,1) }
.rgba-primary-2 { color: rgba(175,196,124,1) }
.rgba-primary-3 { color: rgba( 90,124,  4,1) }
.rgba-primary-4 { color: rgba( 63, 89,  0,1) }



/* Generated by Paletton.com © 2002-2014 */
/* http://paletton.com */